= MAKEDEB(1)
:doctype: manpage
:hardbreaks:
:manmanual: Mist
:mansource: Git

== NAME
mist - The official command-line interface for the makedeb Package Repository

== SYNOPSIS
*mist* clone _pkgbase_ [_options_] ...
*mist* comment _pkgbase_ [_options_] ...
*mist* list _pkgname_ [_options_] ...
*mist* list-comments _pkgbase_ [_options_] ...
*mist* search _query_ ... [_options_] ...
*mist* update
*mist* whoami [_options_] ...

== DESCRIPTION
*mist* is a command-line interface for interacting with the makedeb Package Repository.

The *comment* and *whoami* commands both require authentication via an API key in order to run. An API key can be obtained via the MPR web interface on the user's account page, and can be passed into this program via the *--token* argument or the *MPR_TOKEN* environment variable, the former being described in *OPTIONS*, and the latter in *ENVIRONMENT*.

*clone*::
Clone the build files for a package base from the MPR.

*comment*::
Comment on a package base's page on the MPR.

*list*::
Get information about APT or MPR packages.

*list-comments*::
List comments of a package base on the MPR.

*search*::
Search the package list on the MPR.

*update*::
Updates the APT cache on the system. The MPR cache is not updated as part of this process, as it automatically gets updated when needed commands find it to be old.

*whoami*::
Show the currently authenticated user.

== OPTIONS
Run each command with *--help* to see available options.

== BUGS
Issues, as well as feature requests, should be reported on the project's GitHub page:

https://github.com/makedeb/mist/issues

Matrix is also used as our primary method of real-time communication, being where most discussions (outside of the issue tracker) take place. All rooms are joined via a Matrix space, which can be accessed via the following:

#makedeb:hunterwittenborn.com

== AUTHORS
Hunter Wittenborn <\hunter@hunterwittenborn.com>

A full list of contributors can be found by running *git shortlog -esn* in the Mist's Git repository (linked under *BUGS*).

== SEE ALSO
*makedeb*(8)
